create_clock -name clk -period 1 -waveform {0 0.5} [get_ports "clk"]
set_clock_transition -rise 0.1 [get_clocks "clk"]
set_clock_transition -fall 0.1 [get_clocks "clk"]
set_clock_uncertainty 0.01 [get_ports "clk"]
set_input_delay -max 0.2 [get_ports "cpu_enable"] -clock [get_clocks "clk"]
set_input_delay -max 0.2 [get_ports "sram_enable"] -clock [get_clocks "clk"]
set_input_delay -max 0.2 [get_ports "gpio_enable"] -clock [get_clocks "clk"]
set_input_delay -max 0.2 [get_ports "timer_enable"] -clock [get_clocks "clk"]
set_input_delay -max 0.2 [get_ports "uart_enable"] -clock [get_clocks "clk"]
set_input_delay -max 0.2 [get_ports "async_wakeup"] -clock [get_clocks "clk"]
set_input_delay -max 0.2 [get_ports "test_enable"] -clock [get_clocks "clk"]
set_output_delay -max 0.2 [get_ports "cpu_clk"] -clock [get_clocks "clk"]
set_output_delay -max 0.2 [get_ports "sram_clk"] -clock [get_clocks "clk"]
set_output_delay -max 0.2 [get_ports "gpio_clk"] -clock [get_clocks "clk"]
set_output_delay -max 0.2 [get_ports "timer_clk"] -clock [get_clocks "clk"]
set_output_delay -max 0.2 [get_ports "uart_clk"] -clock [get_clocks "clk"]
set_output_delay -max 0.2 [get_ports "wake_sync"] -clock [get_clocks "clk"]

