
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 29 2026 09:54:20 IST (Aug 29 2026 04:24:20 UTC)

// Verification Directory fv/low_power_soc 

module low_power_soc(clk, rst_n, cpu_enable, sram_enable, gpio_enable,
     timer_enable, uart_enable, async_wakeup, test_enable, cpu_clk,
     sram_clk, gpio_clk, timer_clk, uart_clk, wake_sync, SE, scan_in,
     scan_out, dft_sdi_1, dft_sdo_1);
  input clk, rst_n, cpu_enable, sram_enable, gpio_enable, timer_enable,
       uart_enable, async_wakeup, test_enable, SE, scan_in, dft_sdi_1;
  output cpu_clk, sram_clk, gpio_clk, timer_clk, uart_clk, wake_sync,
       scan_out, dft_sdo_1;
  wire clk, rst_n, cpu_enable, sram_enable, gpio_enable, timer_enable,
       uart_enable, async_wakeup, test_enable, SE, scan_in, dft_sdi_1;
  wire cpu_clk, sram_clk, gpio_clk, timer_clk, uart_clk, wake_sync,
       scan_out, dft_sdo_1;
  wire [1:0] wake_ff;
  wire cpu_en_latched, gpio_en_latched, n_1, n_2, n_3, n_4, n_6, n_7;
  wire n_8, n_9, n_10, n_11, sram_en_latched, timer_en_latched,
       uart_en_latched;
  assign dft_sdo_1 = wake_sync;
  SDFFRHQX1 \wake_ff_reg[0] (.RN (rst_n), .CK (clk), .D (async_wakeup),
       .SI (dft_sdi_1), .SE (SE), .Q (wake_ff[0]));
  AND2XL g195__2398(.A (clk), .B (sram_en_latched), .Y (sram_clk));
  AND2XL g196__5107(.A (clk), .B (timer_en_latched), .Y (timer_clk));
  AND2XL g197__6260(.A (clk), .B (uart_en_latched), .Y (uart_clk));
  AND2XL g198__4319(.A (clk), .B (cpu_en_latched), .Y (cpu_clk));
  AND2XL g199__8428(.A (clk), .B (gpio_en_latched), .Y (gpio_clk));
  SDFFNSRXL cpu_en_latched_reg(.RN (rst_n), .SN (1'b1), .CKN (clk), .D
       (n_9), .SI (scan_in), .SE (SE), .Q (cpu_en_latched), .QN (n_4));
  SDFFNSRXL gpio_en_latched_reg(.RN (rst_n), .SN (1'b1), .CKN (clk), .D
       (n_10), .SI (n_4), .SE (SE), .Q (gpio_en_latched), .QN (n_3));
  SDFFNSRXL sram_en_latched_reg(.RN (rst_n), .SN (1'b1), .CKN (clk), .D
       (n_8), .SI (n_3), .SE (SE), .Q (sram_en_latched), .QN (n_2));
  SDFFNSRXL timer_en_latched_reg(.RN (rst_n), .SN (1'b1), .CKN (clk),
       .D (n_7), .SI (n_2), .SE (SE), .Q (timer_en_latched), .QN (n_1));
  SDFFNSRXL uart_en_latched_reg(.RN (rst_n), .SN (1'b1), .CKN (clk), .D
       (n_11), .SI (n_1), .SE (SE), .Q (uart_en_latched), .QN
       (scan_out));
  NAND2BX1 g210__5526(.AN (uart_enable), .B (n_6), .Y (n_11));
  NAND2BX1 g211__6783(.AN (gpio_enable), .B (n_6), .Y (n_10));
  NAND2BX1 g212__3680(.AN (cpu_enable), .B (n_6), .Y (n_9));
  NAND2BX1 g213__1617(.AN (sram_enable), .B (n_6), .Y (n_8));
  NAND2BX1 g214__2802(.AN (timer_enable), .B (n_6), .Y (n_7));
  SDFFRHQX2 \wake_ff_reg[1] (.RN (rst_n), .CK (clk), .D (wake_ff[0]),
       .SI (wake_ff[0]), .SE (SE), .Q (wake_sync));
  NOR2X4 g216__1705(.A (test_enable), .B (wake_sync), .Y (n_6));
endmodule

