// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Aug 28 2026 23:52:07 IST (Aug 28 2026 18:22:07 UTC)

// Verification Directory fv/low_power_soc 

module low_power_soc(clk, rst_n, cpu_enable, sram_enable, gpio_enable,
     timer_enable, uart_enable, async_wakeup, test_enable, cpu_clk,
     sram_clk, gpio_clk, timer_clk, uart_clk, wake_sync);
  input clk, rst_n, cpu_enable, sram_enable, gpio_enable, timer_enable,
       uart_enable, async_wakeup, test_enable;
  output cpu_clk, sram_clk, gpio_clk, timer_clk, uart_clk, wake_sync;
  wire clk, rst_n, cpu_enable, sram_enable, gpio_enable, timer_enable,
       uart_enable, async_wakeup, test_enable;
  wire cpu_clk, sram_clk, gpio_clk, timer_clk, uart_clk, wake_sync;
  wire [1:0] wake_ff;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, cpu_en_latched, gpio_en_latched, n_1;
  wire n_2, n_3, n_4, n_5, n_6, n_7, n_8, n_9;
  wire n_10, n_11, sram_en_latched, timer_en_latched, uart_en_latched;
  DFFRHQX1 \wake_ff_reg[0] (.RN (rst_n), .CK (clk), .D (async_wakeup),
       .Q (wake_ff[0]));
  AND2XL g181__2398(.A (clk), .B (sram_en_latched), .Y (sram_clk));
  AND2XL g182__5107(.A (clk), .B (timer_en_latched), .Y (timer_clk));
  AND2XL g183__6260(.A (clk), .B (uart_en_latched), .Y (uart_clk));
  AND2XL g184__4319(.A (clk), .B (cpu_en_latched), .Y (cpu_clk));
  AND2XL g185__8428(.A (clk), .B (gpio_en_latched), .Y (gpio_clk));
  DFFNSRX1 cpu_en_latched_reg(.RN (rst_n), .SN (1'b1), .CKN (clk), .D
       (n_11), .Q (cpu_en_latched), .QN (UNCONNECTED));
  DFFNSRX1 gpio_en_latched_reg(.RN (rst_n), .SN (1'b1), .CKN (clk), .D
       (n_10), .Q (gpio_en_latched), .QN (UNCONNECTED0));
  DFFNSRX1 sram_en_latched_reg(.RN (rst_n), .SN (1'b1), .CKN (clk), .D
       (n_9), .Q (sram_en_latched), .QN (UNCONNECTED1));
  DFFNSRX1 timer_en_latched_reg(.RN (rst_n), .SN (1'b1), .CKN (clk), .D
       (n_8), .Q (timer_en_latched), .QN (UNCONNECTED2));
  DFFNSRX1 uart_en_latched_reg(.RN (rst_n), .SN (1'b1), .CKN (clk), .D
       (n_7), .Q (uart_en_latched), .QN (UNCONNECTED3));
  NAND2X1 g231__5526(.A (n_6), .B (n_1), .Y (n_11));
  NAND2X1 g232__6783(.A (n_5), .B (n_1), .Y (n_10));
  NAND2X1 g233__3680(.A (n_4), .B (n_1), .Y (n_9));
  NAND2X1 g234__1617(.A (n_3), .B (n_1), .Y (n_8));
  NAND2X1 g235__2802(.A (n_2), .B (n_1), .Y (n_7));
  NOR2X1 g236__1705(.A (test_enable), .B (cpu_enable), .Y (n_6));
  NOR2X1 g237__5122(.A (test_enable), .B (gpio_enable), .Y (n_5));
  DFFRHQX1 \wake_ff_reg[1] (.RN (rst_n), .CK (clk), .D (wake_ff[0]), .Q
       (wake_sync));
  NOR2X1 g239__8246(.A (test_enable), .B (sram_enable), .Y (n_4));
  NOR2X1 g240__7098(.A (test_enable), .B (timer_enable), .Y (n_3));
  NOR2X1 g241__6131(.A (test_enable), .B (uart_enable), .Y (n_2));
  INVX1 g242(.A (wake_sync), .Y (n_1));
endmodule

